### ISSUE TITLE
groupBy is missing

### ISSUE THREAD

**Issue by andrewthad** [michaelt/streaming-bytestring#1]
Not sure if this is intended, but the docs for `group` explain it as a special case of `groupBy`, but there is no `groupBy`.

**Comment by michaelt** [comment]
Thanks! I think I started with `group` in order to test the implementation - which, as usual, replicates `bytestring` as far as possible -  but was then distracted. http://hackage.haskell.org/package/streaming-bytestring-0.1.4.2/docs/Data-ByteString-Streaming.html#v:groupBy
