### ISSUE TITLE
"fromHandle" should not close the handle upon reaching EOF.

### ISSUE THREAD

**Issue by danidiaz** [michaelt/streaming-bytestring#6]
`fromHandle` should not close the handle when it reaches EOF, as the [corresponding function from pipes-bytestring](http://hackage.haskell.org/package/pipes-bytestring-2.1.4/docs/Pipes-ByteString.html#v:fromHandle) doesn't do so.

Closing the handle can cause problems when we want to implement tail-like functionality for files, in combination with a library like [hinotify](http://hackage.haskell.org/package/hinotify). When new data is added to the file, we can't keep reading from the same handle because it has been closed already.

Closing the handle makes more sense for `hGetContents` because it mimics the lazy I/O function of the same name.

**Comment by michaelt** [comment]
Thanks, @danidiaz ! http://hackage.haskell.org/package/streaming-bytestring-0.1.4.5
